- id: '1603830622083'
  alias: Hall and corridor light
  description: Triggers when there is movement in the hall at ground level or first
    floor. When it freezes, warn with a blue light. Brightness is adapted to the desired
    level. Because the IKEA sensor at the corridor is slow in going to the cleared
    state, have a 10m wait before the Philips sensor at the hall is allowed to clear.
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.hall_motion
    - binary_sensor.corridor_motion
    - binary_sensor.front_door
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.hall_motion
    - binary_sensor.corridor_motion
    for: 00:10:00
    to: 'off'
  - platform: state
    entity_id: binary_sensor.front_door
    for: 00:01:00
    to: 'off'
  condition: []
  action:
  - choose:
    - alias: No movement
      conditions:
      - condition: state
        entity_id: binary_sensor.hall_motion
        state: 'off'
        for: 00:10:00
      - condition: state
        entity_id: binary_sensor.corridor_motion
        state: 'off'
      - condition: state
        entity_id: binary_sensor.front_door
        state: 'off'
        for: 00:01:00
      sequence:
      - service: light.turn_off
        entity_id:
        - light.hall
        - light.corridor
    - alias: Maximum brightness
      conditions:
      - condition: numeric_state
        entity_id: input_number.brightness
        above: '0'
      sequence:
      - service: light.turn_on
        target:
          entity_id:
          - light.hall
        data:
          brightness_pct: '{{ states(''input_number.brightness'') | float }}'
          color_temp: "{% if is_state('binary_sensor.knmi_home_waarschuwing', 'on')\
            \ %}\n  153\n{% elif states('input_number.brightness') | int > 50 %}\n\
            \  360\n{% else %}\n  454\n{% endif %}"
      - service: light.turn_on
        target:
          entity_id:
          - light.corridor
        data:
          brightness_pct: '{{ states(''input_number.brightness'') | float }}'
          color_temp: '{{ 360 if states("input_number.brightness") | int > 50 else
            454 }}'
  mode: queued
  max: 5
- id: '1603831020194'
  alias: Kitchen light
  description: Triggers when there is movement in the kitchen. Only activate light
    when there is less than 20 lux measured in the hall at ground level. Brightness
    is adapted to the desired level.
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: input_number.brightness
        above: '0'
      - condition: state
        entity_id: binary_sensor.kitchen_motion
        state: 'on'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.kitchen
        data:
          brightness_pct: '{{ states(''input_number.brightness'') | float }}'
    default:
    - service: light.turn_off
      entity_id: light.kitchen
  mode: single
- id: '1605426186449'
  alias: Attic motion
  description: Put the light at the second floor on when there is movement in the
    hallway at ground level or first floor. Do so only if there is insufficient light.
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.hall_motion
    - binary_sensor.corridor_motion
  - platform: state
    entity_id: binary_sensor.hall_motion
    to: 'off'
    for: 00:10:00
  - platform: time_pattern
    minutes: '0'
  condition: []
  action:
  - choose:
    - alias: No movement
      conditions:
      - condition: state
        entity_id: binary_sensor.hall_motion
        state: 'off'
        for: 00:10:00
      - condition: state
        entity_id: binary_sensor.corridor_motion
        state: 'off'
      sequence:
      - service: light.turn_off
        entity_id: light.attic
    - alias: On if dark
      conditions:
      - condition: numeric_state
        entity_id: input_number.brightness
        above: '0'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.attic
        data:
          brightness: 100
    default:
    - service: light.turn_off
      entity_id: light.attic
  mode: queued
  max: 5
- id: '1608134139962'
  alias: Shed light
  description: Put the light in the shed on when the door is opened and it is dark.
    Put it off when the door is closed for longer than two minutes. If the door is
    closed, the user is reminded of this automation by a brief flash.
  trigger:
  - platform: state
    entity_id: binary_sensor.shed_door
  - platform: state
    entity_id: binary_sensor.shed_door
    for: 00:02:00
    to: 'off'
  condition: []
  action:
  - choose:
    - alias: Dark and door opened
      conditions:
      - condition: numeric_state
        entity_id: sensor.hall_light
        below: '20'
      - condition: state
        entity_id: binary_sensor.shed_door
        state: 'on'
      sequence:
      - service: light.turn_on
        data: {}
        entity_id: light.shed
    - alias: Door closed for two minutes
      conditions:
      - condition: state
        entity_id: binary_sensor.shed_door
        state: 'off'
        for: 00:02:00
      sequence:
      - service: light.turn_off
        data: {}
        entity_id: light.shed
    - alias: Door closed
      conditions:
      - condition: state
        entity_id: binary_sensor.shed_door
        state: 'off'
      sequence:
      - service: light.turn_on
        entity_id: light.shed
        data:
          flash: short
    default: []
  mode: single
- id: '1609974870568'
  alias: Doorbell
  description: Flash lights and notify when the doorbell is detected by the RTL_433
    extension.
  trigger:
  - platform: device
    domain: mqtt
    device_id: 79ff302733b26ef330b68c020ceedad2
    type: action
    subtype: button_1
    discovery_id: rtl433 1
  condition: []
  action:
  - service: notify.everyone
    data:
      message: Doorbell!
      data:
        group: doorbell
        icon_url: /local/doorbell.png
  - service: light.turn_on
    target:
      entity_id:
      - light.hall
      - light.shed
      - light.attic
    data:
      brightness_pct: 100
      flash: short
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id:
      - light.hall
      - light.attic
      - light.shed
  mode: single
- id: '1612988672846'
  alias: Toilet light
  description: Switch the toilet light when the door is opened.
  trigger:
  - platform: state
    entity_id: binary_sensor.toilet_door
  - platform: state
    entity_id: binary_sensor.toilet_door
    for: 00:05:00
  - platform: time_pattern
    minutes: '0'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.toilet_door
        state: 'off'
        for: 00:05:00
      sequence:
      - service: switch.turn_off
        entity_id: switch.toilet
    - conditions:
      - condition: state
        entity_id: binary_sensor.toilet_door
        state: 'on'
        for: 00:05:00
      sequence:
      - service: switch.turn_off
        entity_id: switch.toilet
    - conditions:
      - condition: state
        entity_id: binary_sensor.toilet_door
        state: 'on'
      sequence:
      - service: switch.turn_on
        data: {}
        entity_id: switch.toilet
  mode: single
- id: '1612988850571'
  alias: Pantry light
  description: Switch the light in the pantry when the door is opened or closed.
  trigger:
  - platform: state
    entity_id: binary_sensor.pantry_door
  - platform: state
    entity_id: binary_sensor.pantry_door
    for: 00:10:00
    to: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.pantry_door
          for: 00:10:00
          state: 'on'
        - condition: state
          entity_id: binary_sensor.pantry_door
          state: 'off'
      sequence:
      - service: light.turn_off
        entity_id: light.pantry
    default:
    - service: light.turn_on
      entity_id: light.pantry
  mode: single
- id: '1612991117230'
  alias: Attic remote
  description: Handles all the events for the attic from a Philips remote. It controls
    one light (short press) and one heater (long press).
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: attic_remote
  condition: []
  action:
  - variables:
      event: '{{ trigger.event.data.event }}'
  - choose:
    - alias: 'On'
      conditions:
      - condition: template
        value_template: '{{ event == 1000 }}'
      sequence:
      - service: light.turn_on
        entity_id: light.attic
      - service: automation.turn_off
        entity_id: automation.attic_motion
    - alias: 'Off'
      conditions:
      - condition: template
        value_template: '{{ event == 4000 }}'
      sequence:
      - service: light.turn_off
        entity_id: light.attic
      - service: automation.turn_on
        entity_id: automation.attic_motion
    - alias: Up
      conditions:
      - condition: template
        value_template: '{{ event == 2002 }}'
      sequence:
      - service: light.turn_on
        entity_id: light.attic
        data:
          brightness_step_pct: 20
    - alias: Down
      conditions:
      - condition: template
        value_template: '{{ event == 3002 }}'
      sequence:
      - service: light.turn_on
        entity_id: light.attic
        data:
          brightness_step_pct: -20
    - alias: Up hold
      conditions:
      - condition: template
        value_template: '{{ event == 2001 }}'
      sequence:
      - service: light.turn_on
        entity_id: light.attic
        data:
          brighness_pct: 100
          color_temp: 300
    - alias: Down hold
      conditions:
      - condition: template
        value_template: '{{ event == 3001 }}'
      sequence:
      - service: light.turn_on
        entity_id: light.attic
        data:
          brightness_pct: 0
          color_temp: 454
    - alias: On hold
      conditions:
      - condition: template
        value_template: '{{ event == 1001 }}'
      sequence:
      - service: climate.turn_on
        entity_id: climate.radiator_attic
    - alias: Off hold
      conditions:
      - condition: template
        value_template: '{{ event == 4001 }}'
      sequence:
      - service: climate.turn_off
        entity_id: climate.radiator_attic
    default: []
  mode: single
- id: '1613577759701'
  alias: Light brightness
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /5
  condition: []
  action:
  - choose:
    - alias: Min
      conditions:
      - condition: time
        after: 01:00:00
        before: 05:00:00
      sequence:
      - service: input_number.set_value
        data:
          value: 1
        target:
          entity_id: input_number.brightness
    - alias: Half
      conditions:
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: '-6'
      sequence:
      - service: input_number.set_value
        data:
          value: 50
        target:
          entity_id: input_number.brightness
    - alias: Max
      conditions:
      - condition: numeric_state
        entity_id: sensor.hall_light
        below: '20'
      sequence:
      - service: input_number.set_value
        data:
          value: 100
        target:
          entity_id: input_number.brightness
    default:
    - service: input_number.set_value
      data:
        value: 0
      target:
        entity_id: input_number.brightness
  mode: single
- id: '1614112596198'
  alias: Bike motion
  description: When it is dark and there is motion, put on the lights in the bike
    shed. Else, put off. Note that this automation can be turned off by  automation.bike_button.
  trigger:
  - platform: state
    entity_id: binary_sensor.bike_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.bike_motion
    to: 'off'
    for: 00:01:00
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.hall_light
        below: '10'
      - condition: state
        entity_id: binary_sensor.bike_motion
        state: 'on'
      sequence:
      - service: switch.turn_on
        entity_id: switch.bike_light
    default:
    - service: switch.turn_off
      entity_id: switch.bike_light
  mode: single
- id: '1614152225581'
  alias: Bike button
  description: When the on button is pressed, put the lights on and disable the motion
    sensor. When the off button is pressed, put the lights off and enable the motion
    sensor after 60 seconds.
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: bike_switch
  condition: []
  action:
  - variables:
      event: '{{ trigger.event.data.event }}'
  - choose:
    - alias: 'On'
      conditions:
      - condition: template
        value_template: '{{ event == 1002 }}'
      sequence:
      - service: switch.turn_on
        entity_id: switch.bike_light
      - service: automation.turn_off
        entity_id: automation.bike_motion
    - alias: On hold
      conditions:
      - condition: template
        value_template: '{{ event == 1001 }}'
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.lounge
      - service: light.turn_on
        target:
          entity_id:
          - light.hall
          - light.kitchen
    - alias: 'Off'
      conditions:
      - condition: template
        value_template: '{{ event == 2002 }}'
      sequence:
      - service: switch.turn_off
        entity_id: switch.bike_light
      - delay:
          minutes: 1
      - service: automation.turn_on
        entity_id: automation.bike_motion
    - alias: Off hold
      conditions:
      - condition: template
        value_template: '{{ event == 2001 }}'
      sequence:
      - service: switch.turn_off
        entity_id: all
      - service: light.turn_off
        entity_id: all
  mode: restart
- id: '1629321154907'
  alias: Terrace light
  description: Control roof terrace LEDs with IKEA remote button.
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: terrace_switch
  condition: []
  action:
  - variables:
      event: '{{ trigger.event.data.event }}'
  - choose:
    - alias: 'On'
      conditions:
      - condition: template
        value_template: '{{ event == 1002 }}'
      sequence:
      - service: light.turn_on
        entity_id: light.terrace
    - alias: 'Off'
      conditions:
      - condition: template
        value_template: '{{ event == 2002 }}'
      sequence:
      - service: light.turn_off
        entity_id: light.terrace
    - alias: On hold
      conditions:
      - condition: template
        value_template: '{{ event == 1001 }}'
      sequence:
      - service: light.turn_on
        entity_id: light.terrace
        data:
          rgbw_color: 255, 255, 255, 255
      - service: automation.turn_on
        target:
          entity_id:
          - automation.attic_motion
          - automation.hall_corridor
        data: {}
    - alias: Off hold
      conditions:
      - condition: template
        value_template: '{{ event == 2001 }}'
      sequence:
      - service: light.turn_off
        target:
          entity_id:
          - light.corridor
          - light.hall
          - light.kitchen
          - light.attic
          area_id:
          - bedroom
        data: {}
      - service: automation.turn_off
        target:
          entity_id:
          - automation.attic_motion
          - automation.hall_corridor
        data: {}
  mode: queued
  max: 25
