- platform: group
  name: Overheating
  unique_id: overheating
  device_class: problem
  entities:
    - binary_sensor.bathroom_overheating
    - binary_sensor.bike_overheating
    - binary_sensor.lounge_overheating
    - binary_sensor.toilet_overheating
- platform: group
  name: Overpowering
  unique_id: overpowering
  device_class: problem
  entities:
    - binary_sensor.bathroom_overpowering
    - binary_sensor.bike_light_overpowering
    - binary_sensor.bike_socket_overpowering
    - binary_sensor.energy_overpowering
    - binary_sensor.lounge_overpowering
    - binary_sensor.terrace_overpowering
    - binary_sensor.toilet_overpowering
- platform: group
  name: Synology problem
  unique_id: synology_problem
  device_class: problem
  entities:
    - binary_sensor.augustinuserf_drive_2_below_min_remaining_life
    - binary_sensor.synology_drive_1_below_min_remaining_life
    - binary_sensor.synology_drive_2_below_min_remaining_life
    - binary_sensor.augustinuserf_drive_2_exceeded_max_bad_sectors
    - binary_sensor.synology_drive_1_exceeded_max_bad_sectors
    - binary_sensor.synology_drive_2_exceeded_max_bad_sectors
    - binary_sensor.augustinuserf_security_status
    - binary_sensor.augustinuserf_security_status
