# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
zha:
  zigpy_config:
    network:
      channel: !secret zigbee_channel
    ota:
      ikea_provider: true
notify:
  - name: everyone
    platform: group
    services:
      - service: mobile_app_samsung
      - service: mobile_app_nokia_7_2
climate:
  - platform: generic_thermostat
    name: Attic climate
    heater: switch.heater
    target_sensor: sensor.attic_temperature
    target_temp: 20
    initial_hvac_mode: "off"
  - platform: generic_thermostat
    name: Bathroom climate
    heater: switch.heater
    target_sensor: sensor.bathroom_temperature
    target_temp: 20
    initial_hvac_mode: "off"
  - platform: generic_thermostat
    name: Bedroom climate
    heater: switch.heater
    target_sensor: sensor.bedroom_temperature
    target_temp: 20
    initial_hvac_mode: "off"
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  measurement_attr: entity_id
  exclude:
    domains:
      - automation
      - persistent_notification
logger:
  default: info
  homeassistant.components.mqtt: debug
homeassistant:
  allowlist_external_dirs:
    - "/config/"
  customize:
    sensor.bedroom_mold:
      icon: mdi:bacteria
    sensor.attic_mold:
      icon: mdi:bacteria
    sensor.lounge_mold:
      icon: mdi:bacteria
    sensor.bathroom_mold:
      icon: mdi:bacteria
    sensor.shed_mold:
      icon: mdi:bacteria
    sensor.guestroom_mold:
      icon: mdi:bacteria
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/25

http:
  ssl_certificate: /ssl/cert.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 3
recorder:
  purge_keep_days: 800
sensor:
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
  - platform: growatt_server
    username: !secret growatt_user
    password: !secret growatt_password
  - platform: template
    sensors:
      outside_temperature:
        friendly_name: "outside temperature"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('weather.home', 'temperature')}}"
        device_class: temperature
      outside_humidity:
        friendly_name: "outside humidity"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('weather.home', 'humidity')}}"
        device_class: humidity
      outside_airpressure:
        friendly_name: "outside pressure"
        unit_of_measurement: "hPa"
        value_template: "{{ state_attr('weather.home', 'pressure')}}"
        device_class: humidity
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /home
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
  - platform: mold_indicator
    name: bedroom_mold
    indoor_temp_sensor: sensor.bedroom_temperature
    indoor_humidity_sensor: sensor.bedroom_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.6
  - platform: mold_indicator
    indoor_temp_sensor: sensor.attic_temperature
    indoor_humidity_sensor: sensor.attic_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.5
    name: attic_mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.bathroom_temperature
    indoor_humidity_sensor: sensor.bathroom_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.5
    name: bathroom_mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.guestroom_temperature
    indoor_humidity_sensor: sensor.guestroom_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.6
    name: guestroom_mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.shed_temperature
    indoor_humidity_sensor: sensor.shed_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.0
    name: shed_mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.lounge_temperature
    indoor_humidity_sensor: sensor.lounge_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.8
    name: lounge_mold
shell_command:
  backup_logs: cp /config/home-assistant.log /config/home-assistant.log.bk
tts:
  - platform: google_translate

script: !include scripts.yaml
automation: !include automations.yaml
