# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages/
  allowlist_external_dirs:
    - "/config/"
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/25
  external_url: https://nieuw-engeland.duckdns.org:8123/
  internal_url: https://192.168.1.251:8123/

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  measurement_attr: entity_id
  include:
    entity_globs:
      - binary_sensor.*_door
      - binary_sensor.*_motion
      - sensor.*_battery_level
      - sensor.*_humidity
      - sensor.*_network_*
      - sensor.*_pressure
      - sensor.*_energy
      - sensor.*_frequency
      - sensor.*_power
      - sensor.*_power_factor
      - sensor.*_voltage
      - sensor.growatt_lifetime_total_energy_input_*
      - sensor.growatt_reactive_voltage
      - sensor.growatt_temperature_*
      - sensor.*_temperature
      - sensor.*_rssi
      - sensor.*_cleaning_area
      - sensor.*_cleaning_time
      - sensor.canon_*
      - sensor.*_co2
      - sensor.*_download
      - sensor.*_ping
      - sensor.*_upload
      - sensor.*_b_received
      - sensor.*_b_sent
      - sensor.*_kib_s_received
      - sensor.*_kib_s_sent
      - sensor.*_uptime
    domains:
      - climate
      - light
      - plant
      - weather
    entities:
      - binary_sensor.experiabox_v10_wan_status
      - input_boolean.shower
      - sensor.cpu_speed
      - sensor.current_power_consumption
      - sensor.disk_free_home
      - sensor.energy_from_grid
      - sensor.energy_to_grid
      - sensor.energy_to_grid
      - sensor.grid_fossil_fuel_percentage
      - sensor.growatt_output_power
      - sensor.growatt_lifetime_energy_output
      - sensor.last_boot
      - sensor.memory_use_percent
      - sensor.power_from_grid
      - sensor.power_production_now
      - sensor.processor_use
      - sensor.relative_marginal_emissions_intensity_nl

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

automation: !include automations.yaml
script: !include scripts.yaml
