# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages/
  allowlist_external_dirs:
    - "/config/"
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/25
  external_url: https://nieuw-engeland.duckdns.org:8123/
  internal_url: http://192.168.1.251:8123/

notify:
  - name: everyone
    platform: group
    services:
      - service: mobile_app_samsung
      - service: mobile_app_nokia_7_2
  - platform: html5
    name: pushnotification
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  measurement_attr: entity_id
  exclude:
    domains:
      - automation
      - persistent_notification

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

recorder:
  purge_keep_days: 800

automation: !include automations.yaml
script: !include scripts.yaml
