# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages/
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
        - 95.99.85.207
        - 192.168.1.170
  customize:
    # Only those that connot be configure using the UI
    sensor.vacuum_cleaning_area:
      unit_of_measurement: "m³"
    sensor.vacuum_cleaning_time:
      unit_of_measurement: "min"
    sensor.washing_machine_flood_battery:
      state_class: measurement

http:
  ip_ban_enabled: false
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.244

automation: !include automations.yaml
script: !include scripts.yaml
