- platform: mold_indicator
  name: bedroom_mold
  indoor_temp_sensor: sensor.bedroom_thermometer
  indoor_humidity_sensor: sensor.bedroom_humidity
  outdoor_temp_sensor: sensor.outside_temperature
  calibration_factor: 1.6
- platform: mold_indicator
  indoor_temp_sensor: sensor.attic_thermometer
  indoor_humidity_sensor: sensor.attic_humidity
  outdoor_temp_sensor: sensor.outside_temperature
  calibration_factor: 1.5
  name: attic_mold
- platform: mold_indicator
  indoor_temp_sensor: sensor.bathroom_thermometer
  indoor_humidity_sensor: sensor.bathroom_humidity
  outdoor_temp_sensor: sensor.outside_temperature
  calibration_factor: 1.5
  name: bathroom_mold
- platform: mold_indicator
  indoor_temp_sensor: sensor.guestroom_thermometer
  indoor_humidity_sensor: sensor.guestroom_humidity
  outdoor_temp_sensor: sensor.outside_temperature
  calibration_factor: 1.6
  name: guestroom_mold
- platform: mold_indicator
  indoor_temp_sensor: sensor.shed_thermometer
  indoor_humidity_sensor: sensor.shed_humidity
  outdoor_temp_sensor: sensor.outside_temperature
  calibration_factor: 1.0
  name: shed_mold
- platform: mold_indicator
  indoor_temp_sensor: sensor.lounge_thermometer
  indoor_humidity_sensor: sensor.lounge_humidity
  outdoor_temp_sensor: sensor.outside_temperature
  calibration_factor: 1.8
  name: lounge_mold
