sensor:
  - platform: mold_indicator
    indoor_temp_sensor: sensor.attic_temperature
    indoor_humidity_sensor: sensor.attic_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.5
    name: Attic mold

alert:
  attic_mold:
    name: Attic mold
    entity_id: binary_sensor.attic_mold
    repeat: 60
    message: "Mold probability in attic is {{ states('sensor.attic_mold') }} %"
    done_message: Mold at attic is unlikely again
    notifiers:
      - mobile_app_sm_a530f
    data:
      channel: attic_mold
      tag: attic_mold
      requireInteraction: true
      sticky: true

homeassistant:
  customize:
    sensor.attic_mold:
      icon: mdi:home-floor-2
      friendly_name: Attic
    alert.attic_mold:
      icon: mdi:bacteria
