sensor:
  - platform: mold_indicator
    indoor_temp_sensor: sensor.attic_thermometer
    indoor_humidity_sensor: sensor.attic_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.5
    name: Attic mold

binary_sensor:
  - platform: threshold
    entity_id: sensor.attic_mold
    upper: 90

alert:
  attic_mold:
    name: Attic mold
    entity_id: binary_sensor.attic_mold
    repeat: 60
    message: "Mold probability in attic is {{ states('sensor.attic_mold') }}"
    done_message: Mold at attic is unlikely again
    notifiers:
      - pushnotification
      - mobile_app_nokia_7_2
    data:
      clickAction: lovelace/thermometer
      channel: attic_mold
      tag: attic_mold
      requireInteraction: true
      url: lovelace/check
      sticky: true
      actions:
        - action: attic_mold
          title: ✅ It's ok!
          icon: mdi:check

homeassistant:
  customize:
    sensor.attic_mold:
      icon: mdi:home-floor-2
      friendly_name: Attic
    alert.attic_mold:
      icon: mdi:bacteria
