sensor:
  - platform: mold_indicator
    indoor_temp_sensor: sensor.bathroom_temperature
    indoor_humidity_sensor: sensor.bathroom_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.5
    name: Bathroom mold

alert:
  bathroom_mold:
    name: Bathroom mold
    entity_id: binary_sensor.bathroom_mold
    repeat: 60
    message: "Mold probability in bathroom is high for over an hour: {{ states('sensor.bathroom_mold') }} %"
    done_message: Mold at bathroom is unlikely again
    skip_first: true
    notifiers:
      - mobile_app_sm_a530f
    data:
      tag: bathroom_mold
      requireInteraction: true
      priority: high

homeassistant:
  customize:
    sensor.bathroom_mold:
      icon: mdi:shower-head
      friendly_name: Bathroom
    alert.bathroom_mold:
      icon: mdi:bacteria
