sensor:
  - platform: mold_indicator
    name: Bedroom mold
    indoor_temp_sensor: sensor.bedroom_temperature
    indoor_humidity_sensor: sensor.bedroom_humidity
    outdoor_temp_sensor: sensor.outside
    calibration_factor: 1.6

alert:
  bedroom_mold:
    name: Bedroom mold
    entity_id: binary_sensor.bedroom_mold
    repeat: 30
    message: "Mold probability in bedroom is high: {{ states('sensor.bedroom_mold') }} %"
    done_message: Mold at bedroom is unlikely again
    notifiers:
      - mobile_app_sm_a530f
    data:
      tag: bedroom_mold
      priority: high

homeassistant:
  customize:
    sensor.bedroom_mold:
      icon: mdi:bed
      friendly_name: Bedroom
    alert.bedroom_mold:
      icon: mdi:bacteria
