sensor:
  - platform: mold_indicator
    indoor_temp_sensor: sensor.lounge_temperature
    indoor_humidity_sensor: sensor.lounge_humidity
    outdoor_temp_sensor: sensor.outside
    calibration_factor: 1.6
    name: Lounge mold

alert:
  lounge_mold:
    name: Lounge mold
    entity_id: binary_sensor.lounge_mold
    repeat: 30
    message: "Mold probability in lounge is high: {{ states('sensor.lounge_mold') }} %"
    done_message: Mold at lounge is unlikely again
    notifiers:
      - mobile_app_sm_a530f
    data:
      tag: lounge_mold
      requireInteraction: true
      priority: high

homeassistant:
  customize:
    sensor.lounge_mold:
      icon: mdi:seat
      friendly_name: Lounge
