esphome:
  name: esp32-poe-iso
  friendly_name: ESP32-PoE-ISO

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EA0JH6eUB0g5p4roO5ZDiB4egyu4VVTFtMt7sOfT8Sg="

ota:
  password: "2f43f324bab52a9cb731beb1081e191f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Poe-Iso Fallback Hotspot"
    password: "RoyJ2iFFe8QM"

captive_portal:
    