substitutions:
  name: tno-esp32-001

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${name}

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid_tno
  password: !secret wifi_password_tno
  ap:
    ssid: ${name}
    password: "00000000"

captive_portal:

api:
  encryption:
    key: LY6QKPRl1xLppNzlszInwWQCKRjLZbQXMt7mMuZs/VY=

ota:
  platform: esphome

logger:

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

external_components:
  - source:
      type: local
      path: my_components

sensor:
  - platform: T9602
    temperature:
      name: temperature
      filters:
        - median:
            window_size: 5
            send_every: 5
            send_first_at: 5
    humidity:
      name: humidity
      filters:
        - median:
            window_size: 5
            send_every: 5
            send_first_at: 5
  - platform: wifi_signal
    name: wifi
  - platform: uptime
    type: seconds
    name: uptime
  - platform: internal_temperature
    name: internal temperature

web_server:
  port: 80
  ota: false
  version: 3
  local: true

esp32_improv:
  authorizer: false