substitutions:
  name: apollo-air-1-bd7c74
  friendly_name: Apollo AIR-1 bd7c74
packages:
  ApolloAutomation.AIR-1: github://ApolloAutomation/AIR-1/Integrations/ESPHome/AIR-1.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: VUH7zZEasnyr0jMUn+GwPyCXrqAiO+EWCCHUlF3bznM=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
