esphome:
  name: co2meter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  password: "7bd5c30456daf623402a60f3a4a388df"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: 192.168.1.222
    gateway: 192.168.1.254
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Device Fallback Hotspot"
    password: "1US2pcggE84J"

captive_portal:

uart:
  rx_pin: 3
  tx_pin: 1
  baud_rate: 9600

sensor:
  - platform: senseair
    co2:
      name: "SenseAir CO2 Value"
      id: senseair_co2_value
    update_interval: 60s
    id: co2
    
i2c:

font:
  - file: "fonts/comic.ttf"
    id: comic
    size: 20

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    lambda: |-
      it.printf(0, 0, id(comic), "%.0f ppm", id(senseair_co2_value).raw_state);
      
button:
  - platform: template
    name: Calibrate sensor
    id: calibrate

    # Optional variables:
    on_press:
      - senseair.background_calibration: co2
      
  - platform: template
    name: Get result calibration
    id: calibrate_result
    on_press:
      - senseair.background_calibration_result: co2