esphome:
  name: flowermeter
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Voltmeter
esp32_ble_tracker:

xiaomi_ble:

sensor:
  - platform: xiaomi_gcls002
    mac_address: "C4:7C:8D:6C:AB:F6"
    temperature:
      name: "Flower Temperature"
    moisture:
      name: "Flower Moisture"
    conductivity:
      name: "Flower Soil Conductivity"
    illuminance:
      name: "Flower Illuminance"
    

# Enable Home Assistant API
api:

ota:
  password: "2a4d238f2f1429b74a198217f6969e68"

wifi:
  ssid: "de Bruin beneden 2.4GHz"
  password: "79CD7C7DA6C9"

  manual_ip:
    static_ip: 192.168.1.221
    gateway: 192.168.1.254
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Flowermeter Fallback Hotspot"
    password: "FxtxXIE9wPJN"



captive_portal:
