esphome:
  name: flowermeter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "T0gvCM5rX2l29NYbTDiZkQ8nUgGKg/JV/DTSEgCIHH0="

ota:
  password: "fd9912f4b8b47312e38e582cd8d061e0"

wifi:
  networks:
    - ssid: de Bruin beneden
      password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.1.180
    gateway: 192.168.1.254
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Flowermeter Fallback Hotspot"
    password: "fTh3PQZZ7nsC"

captive_portal:
    
esp32_ble_tracker:

sensor:
  - platform: xiaomi_gcls002
    mac_address: "94:2B:FF:5C:91:61"
    temperature:
      name: "GCLS02 Temperature"
    moisture:
      name: "GCLS02 Moisture"
    conductivity:
      name: "GCLS02 Soil Conductivity"
    illuminance:
      name: "GCLS02 Illuminance"