esphome:
  name: flowermeter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "T0gvCM5rX2l29NYbTDiZkQ8nUgGKg/JV/DTSEgCIHH0="

ota:
  password: "fd9912f4b8b47312e38e582cd8d061e0"

wifi:
  ssid: "de Bruin boven"
  password: !secret wifi_password
  manual_ip:
    static_ip:  192.168.1.12
    gateway: 10.0.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Flowermeter Fallback Hotspot"
    password: "fTh3PQZZ7nsC"

captive_portal:
    
esp32_ble_tracker:
bluetooth_proxy:
  active: True