substitutions:
  name: muino-water-meter-e5b138
  friendly_name: muino water meter
packages:
  esphome.muino-water-meter: github://martijnvwezel/watermeter-esphome/muino-water-meter-esp32.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: m41egdOPUARcOL/mlgcdexEuYZwBy/K0CjAfcHYohvk=
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
