esphome:
  name: test
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "593793858af0e798e136217482f1c685"

sensor:
  - platform: adc
    pin: 32
    name: Water"
    update_interval: 1s

wifi:
  ssid: "de Bruin beneden 2.4GHz"
  password: "79CD7C7DA6C9"
  manual_ip:
    static_ip: 192.168.1.221
    gateway: 192.168.1.254
    subnet: 255.255.240.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "5Qhv0zKjSLDr"

captive_portal:
