esphome:
  name: tno-gj1
  
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

esp32:
  board: esp32-poe-iso
  framework:
    type: arduino

# Enable logging
logger:

web_server:
  port: 80

sensor:
  - platform: adc
    pin: 33
    name: light
    update_interval: 1s
    attenuation: auto
    
binary_sensor:
  - platform: gpio
    pin:
      number: 14
      mode: 
        input: true
        pulldown: true
    name: motion
    
ota:
  safe_mode: true
  password: !secret ota_password
  
mqtt:
  broker: test.mosquitto.org
  topic_prefix: test23
  # Te volgen op: `mosquitto_sub -h test.mosquitto.org -t "test23/sensor/light/state" -u wildcard -v`