substitutions:
  name: watermeter
  friendly_name: watermeter
packages:
  esphome.muino-water-meter: github://gerritjandebruin/watermeter-esphome/muino-water-meter-esp32.yaml@fix-ha-warnings
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: m41egdOPUARcOL/mlgcdexEuYZwBy/K0CjAfcHYohvk=
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    static_ip: 192.168.1.5
    gateway: 192.168.1.1
    subnet: 255.255.255.0
text_sensor:
  - platform: template
    name: "Firmware version"
    icon: "mdi:git"
    entity_category: "diagnostic"
    lambda: |-
      return {"4.0.11-beta"}; // Manually update this to match what you set above
web_server:
  port: 80
