input_boolean:
  shower:
    name: Shower
    icon: mdi:shower-head

automation:
  - alias: Bathroom
    description: >-
      Put light on when door is opened. Put off when closed for 10 minutes. Put off
      when nothing has changed for 30 minutes, except when showering.
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_door
        to: "off"
        for: "00:10:00"
        id: door long closed
      - platform: state
        entity_id: binary_sensor.bathroom_door
        to: "on"
        id: door opened
      - platform: state
        entity_id: binary_sensor.bathroom_door
        to: "on"
        for: "00:10:00"
        id: door long opened
      - platform: numeric_state
        entity_id: sensor.bathroom_humidity
        below: "80"
        for: "00:00:05"
        id: low humidity
    action:
      - choose:
          - alias: Presumed forgotten to switch light off while door open
            conditions:
              - condition: trigger
                id: door long opened
            sequence:
              - service: switch.turn_off
                entity_id: switch.bathroom
              - service: input_boolean.turn_off
                entity_id: input_boolean.shower
          - alias: Presumed showering
            conditions:
              - condition: trigger
                id: door long closed
              - condition: numeric_state
                entity_id: sensor.bathroom_humidity
                above: "80"
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.shower
              - service: notify.mobile_app_nokia_7_2
                data:
                  title: Shower detected!
                  message: Shower detected!
              - service: switch.toggle
                entity_id: switch.bathroom
              - delay: "00:00:01"
              - service: switch.toggle
                entity_id: switch.bathroom
              - wait_for_trigger:
                  - platform: numeric_state
                    entity_id: sensor.bathroom_humidity
                    below: "80"
              - service: input_boolean.turn_off
                entity_id: input_boolean.shower
          - alias: Presumed forgotten to switch light off while door closed
            conditions:
              - condition: trigger
                id: door long closed
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.bathroom_precence
              - service: switch.turn_off
                entity_id: switch.bathroom
          - alias: Door opened
            conditions:
              - condition: trigger
                id: door opened
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.bathroom_precence
              - service: switch.turn_on
                entity_id: switch.bathroom
    mode: single
