climate:
  - platform: generic_thermostat
    name: Attic
    heater: switch.heater
    target_sensor: sensor.attic_thermometer
    target_temp: 20
  - platform: generic_thermostat
    name: Guestroom
    heater: switch.heater
    target_sensor: sensor.guestroom_thermometer
  - platform: generic_thermostat
    name: Bathroom
    heater: switch.heater
    target_sensor: sensor.bathroom_thermometer
  - platform: generic_thermostat
    name: Bedroom
    heater: switch.heater
    target_sensor: sensor.bedroom_thermometer

homeassistant:
  customize:
    climate.attic:
      icon: mdi:radiator
    climate.guestroom:
      icon: mdi:radiator
    climate.bathroom:
      icon: mdi:radiator
    climate.bedroom:
      icon: mdi:radiator

automation:
  - alias: Climate
    trigger:
      - platform: time
        at: "02:00:00"
    action:
      - service: climate.turn_off
        target:
          entity_id:
            - climate.attic_climate
            - climate.bathroom_climate
