automation:
  - alias: Desk
    description: Handling events from the buttons on the desks.
    trigger:
      - id: north_on
        device_id: edc737eaf70410f77edc47501e93b308
        domain: zha
        platform: device
        type: remote_button_short_press
        subtype: turn_on
      - id: north_off
        device_id: edc737eaf70410f77edc47501e93b308
        domain: zha
        platform: device
        type: remote_button_short_press
        subtype: turn_off
      - id: south_on
        device_id: f2920d964a5c507e42ff8757a220ddb8
        domain: zha
        platform: device
        type: remote_button_short_press
        subtype: turn_on
      - id: south_off
        device_id: f2920d964a5c507e42ff8757a220ddb8
        domain: zha
        platform: device
        type: remote_button_short_press
        subtype: turn_off
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: north_on
            sequence:
              - service: switch.turn_on
                entity_id: switch.desk_north
          - conditions:
              - condition: trigger
                id: north_off
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.desk_north
          - conditions:
              - condition: trigger
                id: south_on
            sequence:
              - service: switch.turn_on
                entity_id: switch.desk_south
          - conditions:
              - condition: trigger
                id: south_off
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.desk_south
