sensor:
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /home
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
command_line:
  - sensor:
      command: "cat /sys/class/thermal/thermal_zone0/temp"
      name: CPU device temperature
      unit_of_measurement: "°C"
      unique_id: hass_cpu
      device_class: temperature
      value_template: "{{ value | multiply(0.001) }}"
