sensor:
  - platform: rest
    name: air_quality_NO2
    resource: https://api.luchtmeetnet.nl/open_api/stations/NL10639/measurements?page=&order=&order_direction=&formula=NO2
    unit_of_measurement: µg/m3
    value_template: "{{ value_json.data[0].value }}"
    scan_interval: 1800
  - platform: rest
    name: air_quality_PM10
    resource: https://api.luchtmeetnet.nl/open_api/stations/NL10639/measurements?page=&order=&order_direction=&formula=PM10
    unit_of_measurement: µg/m3
    value_template: "{{ value_json.data[0].value }}"
    scan_interval: 1800
  - platform: rest
    name: air_quality_PM2P5
    resource: https://api.luchtmeetnet.nl/open_api/stations/NL10636/measurements?page=&order=&order_direction=&formula=PM25
    unit_of_measurement: µg/m3
    value_template: "{{ value_json.data[0].value }}"
    scan_interval: 1800
  - platform: rest
    name: air_quality_O3
    resource: https://api.luchtmeetnet.nl/open_api/stations/NL10639/measurements?page=&order=&order_direction=&formula=O3
    unit_of_measurement: µg/m3
    value_template: "{{ value_json.data[0].value }}"
    scan_interval: 1800
template:
  - sensor:
      - name: "Air quality NO2 index"
        state: >
          {% set NO2 = states('sensor.air_quality_no2') | int(0) %}
          {%- if NO2 | int < 10 -%}
          1 
          {%- elif NO2 | int < 20 -%}
          2
          {%- elif NO2 | int < 30 -%}
          3
          {%- elif NO2 | int < 45 -%}
          4
          {%- elif NO2 | int < 60 -%}
          5
          {%- elif NO2 | int < 75 -%}
          6
          {%- elif NO2 | int < 100 -%}
          7
          {%- elif NO2 | int < 125 -%}
          8
          {%- elif NO2 | int < 150 -%}
          9
          {%- elif NO2 | int < 200 -%}
          10
          {%- else %}
          11
          {%- endif %}
      - name: "Air quality PM10 index"
        state: >
          {% set PM10 = states('sensor.air_quality_pm10') | int(0) %}
          {%- if PM10 | int < 10 -%}
          1 
          {%- elif PM10 | int < 20 -%}
          2
          {%- elif PM10 | int < 30 -%}
          3
          {%- elif PM10 | int < 45 -%}
          4
          {%- elif PM10 | int < 60 -%}
          5
          {%- elif PM10 | int < 75 -%}
          6
          {%- elif PM10 | int < 100 -%}
          7
          {%- elif PM10 | int < 125 -%}
          8
          {%- elif PM10 | int < 150 -%}
          9
          {%- elif PM10 | int < 200 -%}
          10
          {%- else %}
          11
          {%- endif %}
      - name: "Air quality PM25 index"
        state: >
          {% set PM2P5 = states('sensor.air_quality_pm2p5') | int(0) %}
          {%- if PM2P5 | int < 10 -%}
          1 
          {%- elif PM2P5 | int < 15 -%}
          2
          {%- elif PM2P5 | int < 20 -%}
          3
          {%- elif PM2P5 | int < 30 -%}
          4
          {%- elif PM2P5 | int < 40 -%}
          5
          {%- elif PM2P5 | int < 50 -%}
          6
          {%- elif PM2P5 | int < 70 -%}
          7
          {%- elif PM2P5 | int < 90 -%}
          8
          {%- elif PM2P5 | int < 100 -%}
          9
          {%- elif PM2P5 | int < 140 -%}
          10
          {%- else %}
          11
          {%- endif %}
      - name: "Air quality O3 index"
        state: >
          {% set O3 = states('sensor.air_quality_o3') | int(0) %}
          {%- if O3 | int < 15 -%}
          1 
          {%- elif O3 | int < 30 -%}
          2
          {%- elif O3 | int < 40 -%}
          3
          {%- elif O3 | int < 60 -%}
          4
          {%- elif O3 | int < 80 -%}
          5
          {%- elif O3 | int < 100 -%}
          6
          {%- elif O3 | int < 140 -%}
          7
          {%- elif O3 | int < 180 -%}
          8
          {%- elif O3 | int < 200 -%}
          9
          {%- elif O3 | int < 240 -%}
          10
          {%- else %}
          11
          {%- endif %}
      - name: "Air quality combined index"
        state: >
          {% set NO2 = states('sensor.airquality_no2_index') | int(0)  %}
          {% set O3 = states('sensor.airquality_o3_index') | int(0)  %}
          {% set PM10 = states('sensor.airquality_pm10_index') | int(0)  %}

          {%set mylist = states('sensor.airquality_no2_index')|int,
                states('sensor.airquality_o3_index')|int,
                states('sensor.airquality_pm10_index')|int %}

          {% if NO2 | int == O3 | int == PM10 | int -%}
            {% set Index = NO2 | int + 1 %}
            {{Index | int}}
          {%- else -%}
            {{ mylist|max | int }}
          {%- endif %}
