sensor:
  - platform: mold_indicator
    indoor_temp_sensor: sensor.attic_temperature
    indoor_humidity_sensor: sensor.attic_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.5
    name: Attic mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.bathroom_temperature
    indoor_humidity_sensor: sensor.bathroom_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.5
    name: Bathroom mold
  - platform: mold_indicator
    name: Bedroom mold
    indoor_temp_sensor: sensor.bedroom_temperature
    indoor_humidity_sensor: sensor.bedroom_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.6
  - platform: mold_indicator
    indoor_temp_sensor: sensor.guestroom_temperature
    indoor_humidity_sensor: sensor.guestroom_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.6
    name: Guestroom mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.lounge_temperature
    indoor_humidity_sensor: sensor.lounge_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.6
    name: Lounge mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.shed_temperature
    indoor_humidity_sensor: sensor.shed_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.0
    name: Shed mold
