sensor:
  - platform: mold_indicator
    name: Bedroom mold
    indoor_temp_sensor: sensor.bedroom_thermometer
    indoor_humidity_sensor: sensor.bedroom_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.6
  - platform: mold_indicator
    indoor_temp_sensor: sensor.attic_thermometer
    indoor_humidity_sensor: sensor.attic_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.5
    name: Attic mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.bathroom_thermometer
    indoor_humidity_sensor: sensor.bathroom_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.5
    name: Bathroom mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.guestroom_thermometer
    indoor_humidity_sensor: sensor.guestroom_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.6
    name: Guestroom mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.shed_thermometer
    indoor_humidity_sensor: sensor.shed_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.0
    name: Shed mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.lounge_thermometer
    indoor_humidity_sensor: sensor.lounge_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.8
    name: Lounge mold

template:
  binary_sensor:
    - name: Attic mold
      device_class: problem
      state: "{{ states('sensor.attic_mold') | float > 90 }}"
      availability: "{{ not is_state('sensor.attic_mold', 'unavailable') }}"
    - name: Bathroom mold
      device_class: problem
      state: "{{ states('sensor.bathroom_mold') | float > 90 }}"
      availability: "{{ not is_state('sensor.bathroom_mold', 'unavailable') }}"
    - name: Bedroom mold
      device_class: problem
      state: "{{ states('sensor.bedroom_mold') | float > 90 }}"
      availability: "{{ not is_state('sensor.bedroom_mold', 'unavailable') }}"
    - name: Guestroom mold
      device_class: problem
      state: "{{ states('sensor.guestroom_mold') | float > 90 }}"
      availability: "{{ not is_state('sensor.guestroom_mold', 'unavailable') }}"
    - name: Lounge mold
      device_class: problem
      state: "{{ states('sensor.lounge_mold') | float > 90 }}"
      availability: "{{ not is_state('sensor.lounge_mold', 'unavailable') }}"

alert:
  attic_mold:
    name: Attic mold
    entity_id: binary_sensor.attic_mold
    repeat: 60
    message: "Mold probability in attic is {{ states('sensor.attic_mold') }}"
    done_message: Mold at attic is unlikely again
    notifiers:
      - pushnotification
    data:
      tag: attic_mold
      requireInteraction: true
      url: lovelace/check
      priority: high
  bathroom_mold:
    name: Bathroom mold
    entity_id: binary_sensor.bathroom_mold
    repeat: 60
    message: "Mold probability in bathroom is high for over an hour: {{ states('sensor.bathroom_mold') }}"
    done_message: Mold at bathroom is unlikely again
    skip_first: true
    notifiers:
      - pushnotification
    data:
      tag: bathroom_mold
      requireInteraction: true
      url: lovelace/check
      priority: high
  bedroom_mold:
    name: Bedroom mold
    entity_id: binary_sensor.bedroom_mold
    repeat: 30
    message: "Mold probability in bedroom is high: {{ states('sensor.bedroom_mold') }}"
    done_message: Mold at bedroom is unlikely again
    notifiers:
      - pushnotification
    data:
      tag: bedroom_mold
      requireInteraction: true
      url: lovelace/check
      priority: high
  guestroom_mold:
    name: Guestroom mold
    entity_id: binary_sensor.guestroom_mold
    repeat: 30
    message: "Mold probability in guestroom is high: {{ states('sensor.guestroom_mold') }}"
    done_message: Mold at guestroom is unlikely again
    notifiers:
      - pushnotification
    data:
      tag: guestroom_mold
      requireInteraction: true
      url: lovelace/check
      priority: high
  lounge_mold:
    name: Lounge mold
    entity_id: binary_sensor.lounge_mold
    repeat: 30
    message: "Mold probability in lounge is high: {{ states('sensor.lounge_mold') }}"
    done_message: Mold at lound is unlikely again
    notifiers:
      - pushnotification
    data:
      tag: lounge_mold
      requireInteraction: true
      url: lovelace/check
      priority: high

homeassistant:
  customize:
    sensor.bedroom_mold:
      icon: mdi:bed
      friendly_name: Bedroom
    sensor.attic_mold:
      icon: mdi:home-floor-2
      friendly_name: Attic
    sensor.bathroom_mold:
      icon: mdi:shower-head
      friendly_name: Bathroom
    sensor.guestroom_mold:
      icon: mdi:bed-empty
      friendly_name: Guestroom
    sensor.shed_mold:
      icon: mdi:garage
      friendly_name: Shed
    sensor.lounge_mold:
      icon: mdi:seat
      friendly_name: Lounge
