sensor:
  - platform: mold_indicator
    indoor_temp_sensor: sensor.attic_temperature
    indoor_humidity_sensor: sensor.attic_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.5
    name: Attic mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.bathroom_temperature
    indoor_humidity_sensor: sensor.bathroom_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.5
    name: Bathroom mold
  - platform: mold_indicator
    name: Bedroom mold
    indoor_temp_sensor: sensor.bedroom_temperature
    indoor_humidity_sensor: sensor.bedroom_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.6
  - platform: mold_indicator
    indoor_temp_sensor: sensor.guestroom_temperature
    indoor_humidity_sensor: sensor.guestroom_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.6
    name: Guestroom mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.lounge_temperature
    indoor_humidity_sensor: sensor.lounge_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.6
    name: Lounge mold
  - platform: mold_indicator
    indoor_temp_sensor: sensor.shed_temperature
    indoor_humidity_sensor: sensor.shed_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.0
    name: Shed mold

homeassistant:
  customize:
    sensor.attic_mold:
      state_class: measurement
      unit_of_measurement: "%"
      friendly_name: Zolder schimmelkans
      icon: mdi:water-percent-alert
    sensor.bathroom_mold:
      state_class: measurement
      unit_of_measurement: "%"
      friendly_name: Badkamer schimmelkans
      icon: mdi:water-percent-alert
    sensor.bedroom_mold:
      state_class: measurement
      unit_of_measurement: "%"
      friendly_name: Slaapkamer schimmelkans
      icon: mdi:water-percent-alert
    sensor.guestroom_mold:
      state_class: measurement
      unit_of_measurement: "%"
      friendly_name: Gastenkamer schimmelkans
      icon: mdi:water-percent-alert
    sensor.lounge_mold:
      state_class: measurement
      unit_of_measurement: "%"
      friendly_name: Woonkamer schimmelkans
      icon: mdi:water-percent-alert
    sensor.shed_mold:
      state_class: measurement
      unit_of_measurement: "%"
      friendly_name: Schuur schimmelkans
      icon: mdi:water-percent-alert
