template:
  sensor:
    - name: outside temperature
      unit_of_measurement: "°C"
      state: "{{ state_attr('weather.home', 'temperature')}}"
      device_class: temperature
    - name: outside humidity
      unit_of_measurement: "%"
      state: "{{ state_attr('weather.home', 'humidity')}}"
      device_class: humidity
    - name: outside airpressure
      unit_of_measurement: "hPa"
      state: "{{ state_attr('weather.home', 'pressure')}}"
      device_class: humidity

homeassistant:
  customize:
    sensor.outside_temperature:
      icon: mdi:sun-thermometer
