template:
  binary_sensor:
    name: overcurrent
    device_class: problem
    state: "{{ states('sensor.power_from_grid') | float > 6800}}"

alert:
  overcurrent:
    name: Overcurrent
    entity_id: binary_sensor.overcurrent
    repeat: 5
    message: >
      "High total current measured {{ states('sensor.power_from_grid') | float }}"
    notifiers:
      - pushnotification
    data:
      tag: overcurrent
      requireInteraction: true
      url: lovelace/solar
      priority: high
      action: turn_off

automation:
  - alias: Overcurrent
    trigger:
      - platform: event
        event_type: html5_notification.clicked
        event_data:
          action: turn_off
    action:
      - service: climate.turn_off
        target:
          entity_id: all
      - service: light.turn_off
        target:
          entity_id: all
      - service: swtich.turn_off
        target:
          entity_id: all
