binary_sensor:
  - platform: group
    name: Overpowering
    device_class: problem
    entities:
      - binary_sensor.bathroom_overpowering
      - binary_sensor.bike_light_overpowering
      - binary_sensor.bike_socket_overpowering
      - binary_sensor.energy_overpowering
      - binary_sensor.lounge_overpowering
      - binary_sensor.terrace_overpowering
      - binary_sensor.toilet_overpowering

alert:
  overpowering:
    name: Overpowering
    entity_id: binary_sensor.overpowering
    repeat: 30
    message: >
      {% if is_state('binary_sensor.bathroom_overpowering', 'on') %}
        Bathroom
      {% endif %}
      {% if is_state('binary_sensor.bike_light_overpowering', 'on') %}
        Bike light
      {% endif %}
      {% if is_state('binary_sensor.bike_socket_overpowering', 'on') %}
        Bike socket
      {% endif %}
      {% if is_state('binary_sensor.energy_overpowering', 'on') %}
        Energy
      {% endif %}
      {% if is_state('binary_sensor.lounge_overpowering', 'on') %}
        Lounge
      {% endif %}
      {% if is_state('binary_sensor.terrace_overpowering', 'on') %}
        Terrace
      {% endif %}
      {% if is_state('binary_sensor.toilet_overpowering', 'on') %}
        Toilet
      {% endif %}
    notifiers:
      - pushnotification
    data:
      clickAction: lovelace/check
      channel: overpowering
      tag: overpowering
      requireInteraction: true
      importance: high
      priority: high
      url: lovelace/check
      vibrationPattern: 100, 1000, 100, 1000, 100, 1000
      actions:
        - title: ⭘ Turn everything off.
          icon: mdi:power-off
#           action: overpowering

# automation:
#   - alias: Overpowering
#     trigger:
#       - platform: event
#         event_type:
#           - html5_notification.clicked
#           - mobile_app_notification_action
#         event_data:
#           action: overpowering
#     action:
#       - service: climate.turn_off
#         target:
#           entity_id: all
#       - service: light.turn_off
#         target:
#           entity_id: all
#       - service: swtich.turn_off
#         target:
#           entity_id: all
#       - service: media_player.turn_off
#         target:
#           entity_id: media_player.samsung_tv_remote
#       - service: notify.mobile_app_nokia_7_2
#         data:
#           message: clear_notification
#           data:
#             tag: overpowering
#       - service: html5.dismiss
#         data:
#           tag: overpowering
