plant:
  openplantbook:
    client_id: !secret plantbook_client_id
    secret: !secret plantbook_secret

  flower:
    species: yucca elephantipes
    image: openplantbook
    sensors:
      moisture: sensor.flower_moisture
      temperature: sensor.flower_temperature
      conductivity: sensor.flower_soil_conductivity
      brightness: sensor.flower_illuminance
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 8
    max_temperature: 32
    min_brightness: 1500
    max_brightness: 20000
    warn_low_brightness: false

alert:
  plant:
    name: Plant
    entity_id: plant.flower
    state: problem
    skip_first: true
    repeat:
      - 1
      - 480
    message: "Plant: {{ state_attr('plant.flower', 'problem') }}"
    notifiers:
      - pushnotification
      # - mobile_app_sm_a520f
    data:
      tag: plant
      requireInteraction: true
      url: lovelace/plant
      actions: plant_ignore

automation:
  - alias: "Plant acknowledged"
    trigger:
      - platform: event
        event_type: html5_notification.clicked
        event_data:
          action: plant_ignore
    action:
      - service: alert.turn_off
        target:
          entity_id: alert.plant
