sensor:
  - platform: mold_indicator
    indoor_temp_sensor: sensor.attic_temperature
    indoor_humidity_sensor: sensor.attic_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.5
    name: Zolder schimmelkans
  - platform: mold_indicator
    indoor_temp_sensor: sensor.bathroom_temperature
    indoor_humidity_sensor: sensor.bathroom_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.5
    name: Badkamer schimmelkans
  - platform: mold_indicator
    name: Slaapkamer schimmelkans
    indoor_temp_sensor: sensor.bedroom_temperature
    indoor_humidity_sensor: sensor.bedroom_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.6
  - platform: mold_indicator
    indoor_temp_sensor: sensor.guestroom_temperature
    indoor_humidity_sensor: sensor.guestroom_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.6
    name: Gastenkamer schimmelkans
  - platform: mold_indicator
    indoor_temp_sensor: sensor.lounge_temperature
    indoor_humidity_sensor: sensor.lounge_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.6
    name: Woonkamer schimmelkans
  - platform: mold_indicator
    indoor_temp_sensor: sensor.shed_temperature
    indoor_humidity_sensor: sensor.shed_humidity
    outdoor_temp_sensor: sensor.temperature
    calibration_factor: 1.0
    name: Schuur schimmelkans

homeassistant:
  customize:
    sensor.zolder_schimmelkans:
      state_class: measurement
      unit_of_measurement: "%"
      icon: mdi:water-percent-alert
    sensor.badkamer_schimmelkans:
      state_class: measurement
      unit_of_measurement: "%"
      icon: mdi:water-percent-alert
    sensor.slaapkamer_schimmelkans:
      state_class: measurement
      unit_of_measurement: "%"
      icon: mdi:water-percent-alert
    sensor.gastenkamer_schimmelkans:
      state_class: measurement
      unit_of_measurement: "%"
      icon: mdi:water-percent-alert
    sensor.woonkamer_schimmelkans:
      state_class: measurement
      unit_of_measurement: "%"
      icon: mdi:water-percent-alert
    sensor.schuur_schimmelkans:
      state_class: measurement
      unit_of_measurement: "%"
      icon: mdi:water-percent-alert
