template:
  - binary_sensor:
      - name: vacuum low battery
        availability: "{{ not is_state('vacuum.berry', 'unavailable') }}"
        device_class: battery
        state: "{{ state_attr('vacuum.berry', 'battery_level') | float < 10 }}"
        icon: "{{ state_attr('vacuum.berry', 'battery_icon') }}"

alert:
  vacuum:
    name: Vacuum
    entity_id: binary_sensor.vacuum_low_battery
    repeat: 30
    message: "Battery vacuum is almost empty {{ state_attr('vacuum.berry', 'battery_level') }}"
    notifiers:
      - pushnotification
      - mobile_app_sm_a520f
    data:
      clickAction: lovelace/vacuum
      channel: vacuum
      tag: vacuum
      requireInteraction: true
      url: lovelace/vacuum

homeassistant:
  customize:
    alert.vacuum:
      friendly_name: Battery
    sensor.berry_cleaning_area:
      unit_of_measurement: m³
    sensor.berry_cleaning_time:
      unit_of_measurement: min
